### ISSUE TITLE
v1.x of this addon produces invalid/broken CSS in production builds

### ISSUE THREAD

**Issue by runspired** [ember-cli/ember-cli-clean-css#297]
It also doesn't have a clear way to configure it, and even its existence and utilization by the build is hard to learn about.

Related issue: https://github.com/adopted-ember-addons/ember-cli-sass/issues/231

Discord discussion: https://discord.com/channels/480462759797063690/486013244667068436/972196025479593994

Ember Blog refactoring due to bugs this introduces: https://github.com/ember-learn/ember-website/issues/807#issuecomment-824705786

cc @nickschot @acorncom

**Comment by acorncom** [comment]
See also https://github.com/ember-cli/ember-cli-clean-css/pull/278 and https://github.com/ember-cli/ember-cli/issues/8457 for additional backstory

**Comment by kategengler** [comment]
v2.0 of this addon downgraded clean-css to the version used in existing Ember apps, so with that version, this should no longer be true. I am leaving this issue open so that we remember to test this when we do put out a version with a newer clean-css.

**Comment by acorncom** [comment]
@kategengler assume we can close this at this point?
