### ISSUE TITLE
Publish new version with latest clean-css

### ISSUE THREAD

**Issue by kategengler** [ember-cli/ember-cli-clean-css#302]
I'm about to publish a new major version with an old version of clean-css to match the version used by ember-cli-preprocess-registry. 

We should also update to the latest clean-css and publish a new major version after that, so that users can decide to upgrade, if they want. Users will then have to absorb any changes in css output.

**Comment by locks** [comment]
I was tracking down https://github.com/ember-cli/ember-cli/issues/8579 am I'm happy to see we're almost there 🎉

**Comment by SergeAstapov** [comment]
Thank you for pushing this!
with https://github.com/ember-cli/ember-cli-clean-css/releases/tag/v3.0.0 looks like this could be closed?

**Comment by kategengler** [comment]
Yes, thanks!
